Allow spell circles to access player inventory
FallingColors/HexMod pull request #734
Opened 2024-08-23 06:04 UTC by vgskye

fixes #638

2024-08-24 02:23 UTC, SamsTheNerd commented
this code looks basically copy pasted from the player casting env, maybe it should just be abstracted into a shared method somewhere?

2024-08-24 05:10 UTC, vgskye commented
it is based off of that, but there are some behavioural changes(e.g. pull mainhand first then offhand, rather than other-hand-first or other-hand-only since spell circles are hands-free) that I'm not sure makes sense to unify into one set of methods

2024-11-05 18:22 UTC, SamsTheNerd requested changes
i think pulling it out and unifying still makes the most sense. can have it just take a list of hands or something and that should handle that behavior? That seemed like the main thing, was there another issue with unifying it ?

2024-11-12 04:56 UTC, SamsTheNerd reviewed
other than comment I left (which I'm not sure about), code looks fine. Should probably be tested a bit more before merging but I'm not doing that rn

2024-11-12 04:56 UTC, SamsTheNerd commented on Common/src/main/java/at/petrak/hexcasting/api/casting/eval/CastingEnvironment.java
> +                } else {
shouldn't this case check both hands, just prioritizing otherhand. for stuff like self refilling artifacts and whatnot.

2024-11-12 04:56 UTC, SamsTheNerd commented on Common/src/main/java/at/petrak/hexcasting/api/casting/eval/CastingEnvironment.java
> +                } else {
i think having this method take a list of hands to check may be better? that way callers can prioritize whichever hand they want while also being able to decide if they want the other hand used also. then just loop over that list, would probably be neater too.

2024-11-12 04:56 UTC, SamsTheNerd commented on Common/src/main/java/at/petrak/hexcasting/api/casting/eval/CastingEnvironment.java
> +                } else {
not sure that this would ever actually be used in a case like that though

2024-11-12 05:10 UTC, vgskye commented on Common/src/main/java/at/petrak/hexcasting/api/casting/eval/CastingEnvironment.java
> +                } else {
iiuc this is used for Place Block&co, not Recharge&co? I was just retaining previous behaviour when provided with a casting hand though

2024-11-12 07:55 UTC, SamsTheNerd approved these changes

2024-11-12 07:55 UTC, merged