Make Ignite spell compatible with entities
FallingColors/HexMod pull request #746
Opened 2024-08-26 21:29 UTC by miyucomics

Addresses [this suggestion](https://github.com/orgs/FallingColors/projects/5?pane=issue&itemId=49632103) by making the Ignite Block spell able to ignite entities for eight seconds ( the vanilla duration for entities walking into fire ). It renames Ignite Block to just Ignite, adds a new argument type for "an entity *or* a vector", and changes the description for the spell to describe its new capabilities.

2024-09-04 19:25 UTC, object-Object requested changes
One comment about formatting, then I think LGTM.

2024-09-04 19:25 UTC, object-Object commented on Common/src/main/resources/assets/hexcasting/lang/en_us.flatten.json5
Seems like there are a bunch of unnecessary whitespace changes in this file - can  you revert those?

2024-09-21 22:47 UTC, miyucomics commented on Common/src/main/resources/assets/hexcasting/lang/en_us.flatten.json5
I don't think I received an email for this so sorry for the late response. I think IntelliJ automatically formatted the file and I have reversed those changes.

2024-09-28 16:48 UTC, object-Object approved these changes

2024-09-28 16:57 UTC, merged